### PR TITLE
Update mirrorlist

### PR DESCRIPTION
**Pull request by vmmaniac**
Add greek mirror [https://mirrors.sytes.net/chaotic-aur](https://mirrors.sytes.net/chaotic-aur)

### CODE REVIEW

**Comment by dr460nf1r3** [comment]
Hey! :) 
I have a few questions: 
1. How is the mirror syncing? If via rsync, would it be possible to set up Syncthing for mirroring? All other mirrors but CDN ones use this as well and it works very well (syncs faster + allows checking mirror status)
2. I'd add the mirror to our router, so our geo-mirror can use it. The resulting URL would be the one we add to the mirrorlist

Thanks for offering to host a mirror, this helps a lot!

**Comment by Albonycal** [comment]
Hey @vmmaniac how much bandwidth does you mirror have? it's very slow for me 
image

**Comment by vmmaniac** [comment]
Hey @Albonycal
My mirror has a gigabit connection. Maybe it is slow for you because it is located in Greece while you seem to be downloading from an Indian IP

**Comment by Albonycal** [comment]
Yea but still.. it should be faster than that :sweat_smile:

**Comment by vmmaniac** [comment]
Hello @dr460nf1r3 :)

1. The mirror is syncing using a script that when executed, checks whether the lastupdate file has been modified from [builds.garudalinux.org](https://builds.garudalinux.org/repos/chaotic-aur/lastupdate) with a simple HTTP request. If so, it uses rsync to sync from the main node ( rsync://builds.garudalinux.org/chaotic/chaotic-aur/ ). The script is run every minute with a cron job. I don't know if this is acceptable. The docker container will try to obtain an https certificate that I already have and I am already using nginx as a server. Also, the same server is used to host other arch-based mirrors so I am not sure how the docker container will cooperate with the existing setup at the same ports. Tell me if there is anything I can do to help check mirror status! 
2. Feel free to add it to geo-mirror with the appropriate URL

At your disposal for any clarification

**Comment by vmmaniac** [comment]
@Albonycal Ι agree... Is it possible for you to try downloading from somewhere else? Your feedback would be important to me!

**Comment by dr460nf1r3** [comment]
While not being a Syncthing node, this would be sufficient as it would still sync fast enough. Great! :) 

I'll add it to the router soon and will post the URL here afterwards.

**Comment by vmmaniac** [comment]
Great! :) Let me know if you have any problems.

**Comment by Technetium1** [comment]
I get 20-21 MB/s downloading the Arch ISO in Michigan (US), maybe you're having some routing issues @Albonycal?

**Comment by Albonycal** [comment]
image
Hmm it seems fine now? I don't know what happened

**Review by PedroHLC — APPROVED** [review]

**Comment by dr460nf1r3** [comment]
Quick question, is it possible to mirror 2 additional repos of small size? We also distribute a `garuda` and `chaotic-aur-kde` repo using Syncthing which are currently not distributed via rsync. The former is 420 MB in size, and the other will soon contain the kde-git packages of the `chaotic-aur` repo.

**Comment by vmmaniac** [comment]
Regarding the `garuda` and the `chaotic-aur-kde` repos, I believe these are distributed by rsync, too! 
Screenshot_20230222_204005
The structure is the easiest to set up.

**Comment by dr460nf1r3** [comment]
> Sure! No problem mirroring the `garuda` and the `chaotic-aur-kde` repos too!
> 
> But I believe these are distributed via rsync, too! Screenshot_20230222_204005 The structure is the easiest to set up.

I was just going to set it up and noticed it myself :D  

> But if it will cause problems, I can try setting up Syncthing for all 3 mirrors, but I need to experiment with it for a bit before productionsweat_smile

There won't be any issues with using rsync the way you do it, so I guess that is absolutely fine! I was just referring to people using the other 2 repos & `chaotic-mirrorlist` to determine available mirrors :)

**Comment by vmmaniac** [comment]
I am glad to hear that! I fixed the structure and included the other 2 repos as well via rsync. Could you check it and tell me if it is ok?

**Comment by dr460nf1r3** [comment]
Perfect!

**Comment by vmmaniac** [comment]
Congratulations on all your work, and thank you for your patience! I am glad I can help with this project :)

**Comment by dr460nf1r3** [comment]
Everything is perfect by now, you might notice that merging is blocked due to the unsigned first commit tho - sign it (like [this](https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits)) and we are ready to hit the merge button 🥳

**Comment by vmmaniac** [comment]
Thank you so much! I didn't know that you could sign old commits :)

**Comment by dr460nf1r3** [comment]
Here we go, thanks again! :3

**Pull request merged**
