### PR TITLE
Update mirrorlist

### PR DESCRIPTION
**Pull request by taotieren**
Add China https://mirrors.aliyun.com/chaotic-aur/

### CODE REVIEW

**Comment by dr460nf1r3** [comment]
Hey :)
Are you one of the admins of the mirror?

**Comment by dr460nf1r3** [comment]
I would love to add the mirror, however some information are missing. It would be great if they could be provided :)

**Comment by taotieren** [comment]
Sorry, I am not the mirror administrator of aliyun. This is the email address of Aliyun's external communication: ali-yum@alibaba-inc.com.

**Comment by dr460nf1r3** [comment]
Alright, I got the information I needed nevertheless. Thanks!

**Pull request merged**
